# Task 1
### create 2d array from 1,12 range 
    # dimension should be 6row 2 columns  
    # and assign this array values in x values in x variable
    # Hint: you can use arange and reshape numpy methods  
    x =  np.arange(1,13).reshape((6,2)) 

In [1]:
import numpy as np

In [2]:
x=np.arange(1,13).reshape(6,2)

In [3]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# Task 2
create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape 

    x = np.arange(1,28,dtype=np.float64).reshape((3,3,3))     

In [4]:
x=np.arange(10,37)

In [5]:
np.ascontiguousarray(x, dtype=np.float64)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36.])

In [6]:
np.reshape((x),( 3,3,3))

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

# Task 3

In [7]:
a = np.arange(1, 100*10+1).reshape((100,10))

In [8]:
a

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
       [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
       [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
       [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
       [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
       [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
       [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
       [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
       [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100],
       [ 101,  102,  103,  104,  105,  106,  107,  108,  109,  110],
       [ 111,  112,  113,  114,  115,  116,  117,  118,  119,  120],
       [ 121,  122,  123,  124,  125,  126,  127,  128,  129,  130],
       [ 131,  132,  133,  134,  135,  136,  137,  138,  139,  140],
       [ 141,  142,  143,  144,  1

In [9]:
 np.multiply.outer(a*5, a*7)


array([[[[      35,       70,      105, ...,      280,      315,
               350],
         [     385,      420,      455, ...,      630,      665,
               700],
         [     735,      770,      805, ...,      980,     1015,
              1050],
         ...,
         [   33985,    34020,    34055, ...,    34230,    34265,
             34300],
         [   34335,    34370,    34405, ...,    34580,    34615,
             34650],
         [   34685,    34720,    34755, ...,    34930,    34965,
             35000]],

        [[      70,      140,      210, ...,      560,      630,
               700],
         [     770,      840,      910, ...,     1260,     1330,
              1400],
         [    1470,     1540,     1610, ...,     1960,     2030,
              2100],
         ...,
         [   67970,    68040,    68110, ...,    68460,    68530,
             68600],
         [   68670,    68740,    68810, ...,    69160,    69230,
             69300],
         [   69370,    6

# Task 4

In [10]:
arr = np.arange(9).reshape(3,3)

In [11]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr[:,[0, 1]] = arr[:,[1, 0]]

In [13]:
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# Task 5

In [14]:
z=np.zeros(20).reshape(4,5)

In [15]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Task 6

In [16]:
arr=np.zeros(10)

In [17]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
arr[5]=10
arr[8]=20

In [19]:
arr

array([ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.])

# Task 7

In [20]:
 x = np.arange(4, dtype=np.int64)

In [21]:
x

array([0, 1, 2, 3], dtype=int64)

In [22]:
np.full_like(x,0)

array([0, 0, 0, 0], dtype=int64)

# Task 8  
#### Create a new array of 2x5 uints, filled with 6

In [23]:
x=np.full((2,5),6)  

In [24]:
x

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

# Task 9
#### Create an array of 2, 4, 6, 8, ..., 100.

In [25]:
a=np.arange(2,101)

In [26]:
a

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

# Task 10
#### Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.

In [27]:
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
brr = np.array([1,2,3])
sub= arr - brr[:,np.newaxis]

In [28]:
sub

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

# Task 11
###Replace all odd numbers in arr with -1 without changing arr

In [29]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[arr%2==1] =-1 

In [32]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Task 12 
###Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.

In [33]:
arr = np.array([1,2,3])

In [34]:
arr

array([1, 2, 3])

In [35]:
np.r_[np.repeat(arr, 3), np.tile(arr, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# Task 13
###Set a condition which gets all items between 5 and 10 from arr.

In [36]:
import numpy as np

In [37]:
 arr = np.array([2, 6, 1, 9, 10, 3, 27])

In [38]:
ans = arr[(arr>5) & (arr<10)]

In [39]:
ans

array([6, 9])

# Task 14
###Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method


In [40]:
import numpy as np

In [41]:
arr = np.arange(10, 34, 1).reshape(8,3)

In [42]:
arr

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [43]:
np.array_split(arr,4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

# Task 15
####Sort following NumPy array by the second column

In [44]:
 arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])

In [45]:
arr

array([[ 8,  2, -2],
       [-4,  1,  7],
       [ 6,  3,  9]])

In [46]:
np.sort(arr, axis=0)

array([[-4,  1, -2],
       [ 6,  2,  7],
       [ 8,  3,  9]])

# Task 16
####Write a NumPy program to join a sequence of arrays along depth

In [47]:
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])

In [48]:
arr = np.dstack((x, y))

In [50]:
arr

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

# Task 17
#### replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where

In [51]:
import numpy as np

In [52]:
arr = np.arange(1,10*10+1).reshape((10,10))

In [53]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [54]:
ans=np.where(arr%3==0,"Yes","No")

In [55]:
ans

array([['No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No']],
      dtype='<U3')

In [56]:
ans=np.where(arr%5==0,"Yes","No")

In [57]:
ans

array([['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes'],
       ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes']],
      dtype='<U3')

# Task 18
 ### count values of "students" are exist in "piaic"

In [58]:
piaic = np.arange(100)
students = np.array([5,20,50,200,301,7001])


In [59]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# Task 19
#Create variable "X" from 1,25 (both are included) range values
    #Convert "X" variable dimension into 5 rows and 5 columns
    #Create one more variable "W" copy of "X" 
    #Swap "W" row and column axis (like transpose)
    # then create variable "b" with value equal to 5
    # Now return output as "(X*W)+b:

In [60]:
X =   # Write your code here
    W =   # Write your code here 
    b =   # Write your code here

SyntaxError: invalid syntax (<ipython-input-60-3d3fd6f445c3>, line 1)

In [61]:
x=np.arange(1,26).reshape(5,5)

In [62]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
W=np.copy(x)

In [64]:
W

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [65]:
W.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [66]:
b=np.array(5)

In [67]:
b

array(5)

In [68]:
outPut=(x*W)+b

In [69]:
outPut

array([[  6,   9,  14,  21,  30],
       [ 41,  54,  69,  86, 105],
       [126, 149, 174, 201, 230],
       [261, 294, 329, 366, 405],
       [446, 489, 534, 581, 630]])

# Task 20
 #apply fuction "abc" on each value of Array "X"
 ###fucntion20():
    #apply fuction "abc" on each value of Array "X"
    x = np.arange(1,11)
    def xyz(x):
        return x*2+3-2

    return #Write your Code here
#Expected Output: array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [70]:
x = np.arange(1,11)

In [71]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
return=(x*2+3-2)

SyntaxError: invalid syntax (<ipython-input-72-a3f5d0be9165>, line 1)